from __future__ import annotations

import logging
from pathlib import Path

from agent import git_utils
from agent.graph import build_graph
from agent.state import ChangedFile, FileWorkItem  # noqa: F401 (FileWorkItem re-used in type hints)
from agent.tools import detect_language
from app.config import settings
from app.git_ops import cleanup, clone_pr, push_tests_branch
from app.models import DeliveryReport, PRPayload
from app.scm.factory import get_client

log = logging.getLogger(__name__)

SOURCE_EXTS = {".py", ".js", ".jsx", ".ts", ".tsx", ".java", ".go", ".rb"}


def _looks_like_test(path: str) -> bool:
    p = path.lower()
    return (
        "/test" in p
        or p.startswith("test")
        or p.endswith("_test.py")
        or p.endswith(".test.js")
        or p.endswith(".test.ts")
        or p.endswith(".spec.js")
        or p.endswith(".spec.ts")
    )


def _filter_source_files(files: list[str]) -> list[str]:
    return [f for f in files if Path(f).suffix.lower() in SOURCE_EXTS and not _looks_like_test(f)]


def _build_pr_body(report: DeliveryReport) -> str:
    lines = [
        f"🤖 Automated test generation for PR #{report.pr_number}",
        "",
        f"**Existing suite:** {report.existing_suite_summary or 'not run'}",
        "",
        "## Generated tests",
    ]
    if not report.files_generated:
        lines.append("_None — no coverage gaps detected._")
    else:
        for f in report.files_generated:
            lines.append(f"- `{f}`")

    if report.files_skipped_covered:
        lines.append("")
        lines.append("## Skipped (already covered)")
        for f in report.files_skipped_covered:
            lines.append(f"- `{f}`")

    if report.suspicious_flags:
        lines.append("")
        lines.append("## ⚠ Suspicious behavior changes flagged for review")
        for flag in report.suspicious_flags:
            lines.append(f"- **`{flag['file']}`** — {flag['reasoning']}")

    lines.append("")
    lines.append("---")
    lines.append("_Generated by the Unit Test Generator agent (LangChain + LangGraph)._")
    return "\n".join(lines)


def run_pipeline(payload: PRPayload) -> DeliveryReport:
    """End-to-end: clone → run graph → push tests → open PR → comment suspicious."""
    log.info("pipeline start: %s PR #%s", payload.scm, payload.pr_number)
    scm = get_client(payload.scm)
    report = DeliveryReport(pr_number=payload.pr_number, scm=payload.scm)

    repo_path: Path | None = None
    try:
        repo_path = clone_pr(
            payload.clone_url, payload.base_ref, payload.head_ref, payload.head_sha
        )

        try:
            changed = git_utils.changed_files_between(
                repo_path, f"origin/{payload.base_ref}", payload.head_sha
            )
        except git_utils.GitError as exc:
            log.warning("changed_files_between failed: %s; falling back", exc)
            changed = git_utils.changed_files_between(
                repo_path, payload.base_sha, payload.head_sha
            )

        source_files = _filter_source_files(changed)
        if not source_files:
            log.info("no source files changed; nothing to do")
            scm.post_pr_comment(
                payload,
                "🤖 Test-gen bot: no source files changed in this PR — skipping.",
            )
            return report

        if len(source_files) > settings.max_files_per_pr:
            log.info("PR touches %d source files > cap %d; truncating",
                     len(source_files), settings.max_files_per_pr)
            source_files = source_files[: settings.max_files_per_pr]

        seed_items = [
            FileWorkItem(
                file=ChangedFile(
                    path=f,
                    language=detect_language(f),
                    tier="tier2",
                    base_content=None,
                    head_content=None,
                    existing_tests=None,
                )
            )
            for f in source_files
        ]

        graph = build_graph()
        final_state = graph.invoke(
            {
                "repo_path": str(repo_path),
                "pr_context": {
                    "title": payload.pr_title,
                    "body": payload.pr_body,
                    "base_ref": f"origin/{payload.base_ref}",
                    "head_ref": payload.head_sha,
                },
                "validate": True,
                "max_attempts": settings.max_attempts,
                "deliver_mode": "scm",
                "work_items": seed_items,
                "current_index": 0,
                "errors": [],
            },
            config={"recursion_limit": 200},
        )

        suite = final_state.get("existing_suite", {})
        if suite.get("ran"):
            report.existing_suite_summary = (
                f"{suite.get('detected_runner')}: "
                f"{suite.get('passed', 0)} passed / {suite.get('failed', 0)} failed"
            )
            if suite.get("failed_tests"):
                report.existing_suite_summary += (
                    f" — FAILED: {', '.join(suite['failed_tests'][:5])}"
                )
        else:
            report.existing_suite_summary = f"not run ({suite.get('stderr', 'no runner detected')})"

        files_to_push: dict[str, str] = {}
        for item in final_state["work_items"]:
            src_path = item["file"]["path"]
            code = item.get("test_code")
            status = item.get("status", "")
            if status == "no_gaps":
                report.files_skipped_covered.append(src_path)
                continue
            if not code:
                continue
            files_to_push[item["test_path"]] = code
            report.files_generated.append(item["test_path"])

            cls = item.get("failure_classification") or {}
            if cls.get("verdict") == "suspicious":
                report.suspicious_flags.append({
                    "file": src_path,
                    "reasoning": cls.get("reasoning", ""),
                })

        if files_to_push:
            tests_branch = f"testgen/pr-{payload.pr_number}-{payload.head_sha[:7]}"
            report.tests_branch = tests_branch
            push_tests_branch(
                repo_path,
                new_branch=tests_branch,
                from_ref=payload.head_sha,
                files=files_to_push,
                commit_message=f"tests: auto-generated for PR #{payload.pr_number}",
            )
            pr_body = _build_pr_body(report)
            report.tests_pr_url = scm.open_follow_up_pr(
                payload,
                source_branch=tests_branch,
                title=f"🤖 Generated tests for #{payload.pr_number}",
                body=pr_body,
            )
        else:
            scm.post_pr_comment(
                payload,
                "🤖 Test-gen bot: no coverage gaps found — existing tests cover the diff.",
            )

        for flag in report.suspicious_flags:
            scm.post_pr_comment(
                payload,
                (
                    f"⚠ **Test-gen bot flagged a suspicious change in `{flag['file']}`.**\n\n"
                    f"{flag['reasoning']}\n\n"
                    "The regression tests derived from the base branch failed against this "
                    "diff, and the PR title/body did not clearly justify the behavior change. "
                    "Please review whether this change is intentional."
                ),
            )

        log.info("pipeline done: %s", report)
        return report

    finally:
        if repo_path:
            cleanup(repo_path)
